In [1]:
# Object Oriented Programming 

In [2]:
class phone:
    def make_call(self):
        print("I am making a call")
    def play_game(self):
        print("I am playnig a game")

In [3]:
p1 = phone()

In [4]:
p1.make_call()

I am making a call


In [5]:
p1.play_game()

I am playnig a game


In [12]:
class phone:
    def set_color(self, color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print("make call")
    def play_game(self):
        print("play game")

In [13]:
p2 = phone()

In [14]:
p2.set_color("blue")

In [16]:
p2.set_cost(5000)

In [17]:
p2.show_color()

'blue'

In [18]:
p2.show_cost()

5000

In [19]:
p2.make_call()

make call


In [20]:
p2.play_game()

play game


In [ ]:
# Constructor

In [21]:
class Employee:
    def __init__(self,name,age, gender, salary):
        self.name = name
        self.age = age
        self.gender = gender
        self.salary = salary
    
    def show_employee_details(self):
        print("Name of Employee: ", self.name)
        print("Age: ", self.age)
        print("Gender: ", self.gender)
        print("salary: ", self.salary)

In [23]:
e1 = Employee("Ram", 35, "Male", 25000)

In [24]:
e1.show_employee_details()

Name of Employee:  Ram
Age:  35
Gender:  Male
salary:  25000


In [5]:
# example of singal inheritance 

class Vehicle:
    def __init__(self, mileage, cost):
        self.mileage = mileage
        self.cost = cost
        
    def show_vehicle_details(self):
        print("mileage of vehicle: ", self.mileage)
        print("cost of vehile: ", self.cost)
        print("i am vehicle")

In [18]:
v1 = Vehicle(300, 500)

In [17]:
#over riding __init__ method using super()

class Car(Vehicle):
    def __init__(self, mileage, cost, tyres, hp):
        super().__init__(mileage, cost)
        self.tyres = tyres
        self.hp = hp
        
    def show_car_details(self):
        print("i am a car")
        print("Number of tyres are ", self.tyres)
        print("Value of hourse power is", self.hp)

In [20]:
c1 = Car(600,120000000,8 , 999)

In [21]:
c1.show_car_details()

i am a car
Number of tyres are  8
Value of hourse power is 999


In [22]:
c1.show_vehicle_details()

mileage of vehicle:  600
cost of vehile:  120000000
i am vehicle


In [ ]:
# types of Inheritance 
# multiple inheritance 

In [12]:
class Parent1:
    def assign_string_one(self, str1):
        self.str1 = str1
    def show_string_one(self):
        return self.str1

In [13]:
class Parent2:
    def assign_string_two(self, str2):
        self.str2 = str2
    def show_string_two(self):
        return self.str2

In [15]:
class child (Parent1, Parent2):
    def assign_string_three(self, str3):
        self.str3 = str3
    def show_string_three(self):
        return self.str3

In [16]:
my_child = child()

In [17]:
my_child.assign_string_one("I am string of parent one")

In [18]:
my_child.assign_string_two("I am string of parent two")

In [19]:
my_child.assign_string_three("I am string of child")

In [20]:
my_child.show_string_one()

'I am string of parent one'

In [21]:
my_child.show_string_two()

'I am string of parent two'

In [22]:
my_child.show_string_three()

'I am string of child'

In [ ]:
# Multi-level Inheritance

In [23]:
class Parent:
    def get_name(self, name):
        self.name = name
    def show_name(self):
        return self.name

In [26]:
class Child(Parent):
    def get_age(self, age):
        self.age = age
    def show_age(self):
        return self.age
        

In [28]:
class GrandChild(Child):
    def get_gender(self, gender):
        self.gender = gender
    def show_gender(self):
        return self.gender

In [29]:
gc = GrandChild()

In [30]:
gc.get_name("Dipika")

In [31]:
gc.get_age(26)

In [32]:
gc.get_gender("female")

In [33]:
gc.show_name()

'Dipika'

In [34]:
gc.show_age()

26

In [35]:
gc.show_gender()

'female'

In [ ]:
# libraries of Python 
#1 Pandas 2 Numpy 3 Metplotlib  

In [ ]:
#1 Numpy Libraries

In [1]:
import numpy as np

In [2]:
li =[1,2,3,4]

In [3]:
n1= np.array(li)

In [4]:
n1

array([1, 2, 3, 4])

In [5]:
type(n1)

numpy.ndarray

In [7]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [8]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [9]:
type(n2)

numpy.ndarray

In [ ]:
# initializing Numpy Array
#Zeros method

In [10]:
n3= np.zeros((2,3))

In [11]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
type(n3)

numpy.ndarray

In [14]:
n4= np.zeros((10,10))

In [15]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
type(n4)

numpy.ndarray

In [ ]:
# intializing numpy array with samr number

In [19]:
n5 = np.full((3,3), 10)

In [20]:
n5

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
# intializing Numpy array with a range

In [21]:
n6= np.arange (10,100,10)

In [22]:
n6

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
n7= np.arange(5,25,5)

In [24]:
n7

array([ 5, 10, 15, 20])

In [ ]:
# intializing Numpy array with random number

In [30]:
np.random.randint(10,20,3)

array([17, 12, 12])